/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MenuCategory = { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'snacks' : null } |
  { 'dinner' : null } |
  { 'beverages' : null };
export interface MenuItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : [] | [string],
  'category' : MenuCategory,
  'price' : number,
}
export interface OrderItem { 'quantity' : bigint, 'menuItemId' : string }
export interface OrderRecord {
  'id' : string,
  'status' : OrderStatus,
  'customer' : Principal,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'ready' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[OrderRecord], undefined>,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getAvailableMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItem' : ActorMethod<[string], [] | [MenuItem]>,
  'getMenuItemsByCategory' : ActorMethod<[MenuCategory], Array<MenuItem>>,
  'getOrder' : ActorMethod<[string], [] | [OrderRecord]>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<OrderRecord>>,
  'getUserOrders' : ActorMethod<[], Array<OrderRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'toggleMenuItemAvailability' : ActorMethod<[string], undefined>,
  'updateMenuItem' : ActorMethod<[string, MenuItem], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];