/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuCategory = IDL.Variant({
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'snacks' : IDL.Null,
  'dinner' : IDL.Null,
  'beverages' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : MenuCategory,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'ready' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'menuItemId' : IDL.Text,
});
export const OrderRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([OrderRecord], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getAvailableMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [MenuCategory],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderRecord)], ['query']),
  'getOrdersByStatus' : IDL.Func(
      [OrderStatus],
      [IDL.Vec(OrderRecord)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'toggleMenuItemAvailability' : IDL.Func([IDL.Text], [], []),
  'updateMenuItem' : IDL.Func([IDL.Text, MenuItem], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuCategory = IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'snacks' : IDL.Null,
    'dinner' : IDL.Null,
    'beverages' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : MenuCategory,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'ready' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'quantity' : IDL.Nat,
    'menuItemId' : IDL.Text,
  });
  const OrderRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([OrderRecord], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getAvailableMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [MenuCategory],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderRecord)], ['query']),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [IDL.Vec(OrderRecord)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'toggleMenuItemAvailability' : IDL.Func([IDL.Text], [], []),
    'updateMenuItem' : IDL.Func([IDL.Text, MenuItem], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };